apiVersion: v1
kind: ConfigMap
metadata:
  name: bh-core-config
data:
  PORT: "3000"
  DB_HOST: "bh-core-db-service"
  DB_PORT: "5432"
  DB_NAME: "bh_core_db"
  DB_USER: "postgres"
  AUDIT_URL: "http://bh-audit-service:3001/api/v1/audit/events"
  JWT_EXPIRES_IN: "24h"
